[package]
name = "rusty-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.0"
tokio = {version = "1.22.0", features = ["full"]}
clap = {version = "4.0.0", features = ["cargo", "derive"]}
rand = "0.8.5"

[dev-dependencies]
anyhow = "1.0.0"
